### ISSUE TITLE
Displaying the output for the first run

### ISSUE THREAD

**Issue by th0th** [markwragg/PowerShell-Watch#2]
Greetings Mark, thanks for making this available 💐

Is there a way to display the output for the initial run? E.g.

```powershell
Get-ChildItem | Watch-Command -Continuous
```
waits for directory contents to change before displaying anything.

**Comment by markwragg** [comment]
Hi @th0th,

I have just added a `-PassThru` switch to the command, which then returns the initial result as you requested:

```
Get-ChildItem | Watch-Command -Continuous -PassThru
```

This is published in the PowerShell Gallery as version [1.0.30](https://www.powershellgallery.com/packages/Watch/1.0.30), so you should just be able to do `Update-Module Watch` to get the change if you installed via the Gallery.

Let me know if you find any issues with it.

Thanks for the suggestion!

Mark
