### ISSUE TITLE
Clear-Host only when differences

### ISSUE THREAD

**Issue by ZHider** [markwragg/PowerShell-Watch#4]
I am using the watch-command module to track changes in catalog files. I've noticed that with the -ClearScreen parameter, the screen is cleared every time a comparison is made. And if the object being compared is not updated as fast as the wc-command comparison, the entire terminal is empty in the one loop where the object being compared has not changed.
So I would like to clear-host only when there is a change in the comparison, and then output the result.

I'm a beginner in powershell, so if you have any questions, feel free to ask, thanks!

**Comment by markwragg** [comment]
Thanks for the contribution. I don't think a new parameter is necessary though, I can't see any reason why we shouldn't just move the existing `$ClearScreen` logic to where you've put `$ClearScreenIfDifferent`, which is a better placement.

**Comment by markwragg** [comment]
@ZHider I saw you closed your PR. If you want to reopen it by modify it per the above I'll happily merge it.

**Comment by ZHider** [comment]
Thank you for your reply! I'm more accustomed to using overwatch on linux, so I haven't figured out what the original clear-host usage scenarios were. I didn't modify the original clear-host logic out of an abundance of caution. I'm relieved to hear you say that.
I've re-opened my PR, so please merge if you think it's appropriate. :)

**Comment by markwragg** [comment]
Thanks again for the contribution! This is now published to the gallery as module version 1.0.31: https://www.powershellgallery.com/packages/Watch/1.0.31

**Comment by markwragg** [comment]
Implemented
